services:
  backend:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=80
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_HOST=db.domain
      - DB_NAME=watch_db
      - ORIGINS=*
    depends_on:
      - db
    networks:
      inner_network:
        aliases:
          - backend.domain

  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    networks:
      inner_network:
        aliases:
          - frontend.domain

  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=watch_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      inner_network:
        aliases:
          - db.domain

volumes:
  db_data:

networks:
  inner_network: